module.exports = {
    "220 вольт" : "220-volt.ru",
    "все инструменты" : "vseinstrumenti.ru",
    "беру" : "beru.ru",
    "кувалда" : "kuvalda.ru",
    "леруа мерлен" : "leroymerlin.ru",
    "бауцентр" : "baucenter.ru",
    "технопоинт" : "technopoint.ru",
    "днс" : "dns-shop.ru",
    "арсенал трейдинг" : "tdarsenal.ru",
    "анталекс"  : "antaleks.rf",
    "castorama"  : "castorama.ru",
    "obi"  : "obi.ru",
    "ситилинк"  : "citilink.ru",
    "юлмарт"  : "ulmart.ru",
    "элитех"  : "elitech-m.ru",
    "макита-про"  : "makitapro.ru",
    "эльдорадо (003)"  : "eldorado.ru",
    "23киловатт"  : "23kw.ru",
    "ozon"  : "ozon.ru",
    "юлмарт"  : "ulmart.ru",
    "котофото"  : "kotofoto.ru", 
    "elmall23"  : "elmall23.ru", 
    "онлайн трейд"  : "onlinetrade.ru",
    "ударник"  : "udarnik74.ru", 
    "metabo.su"  : "metabo.su", 

}